### ISSUE TITLE
Find and Fix Bugs | Start here

### ISSUE THREAD

**Issue by demilolu** [Call-for-Code-for-Racial-Justice/Legit-Info#100]
## Background

This issue provides directions on how you can contribute to Legit-Info by documenting bugs and fixing them. Please keep this issue open.

## Tasks

- [ ] Check out the open issues, ensure you're not replicating existing issues
- [ ] Read & follow the instructions in the [Getting Started section ](https://github.com/Call-for-Code-for-Racial-Justice/Legit-Info#getting-started)of the readme.md to set the solution up  

As you run across any bugs (error messages, etc)
- [ ] if your issue is more of a suggestion for improving the UI go to this issue instead
- [ ] create a new issue using the bug template
- [ ] label it 'hacktoberfest', 'bug' 
- [ ] Discuss the bug you found in the issue with @upkarlidder @tonypearson @demilolu 

If you are able to fix the bug
- [ ] assign yourself to the issue
- [ ] add details on your proposed fix to the issue
- [ ] Discuss the issue  with @upkarlidder @tonypearson @demilolu 
- [ ] submit a pull request to main branch
- [ ] PR merged by Legit-Info team
- [ ] Congratulations! 

If you are unfamilar with pull requests, committing code on Github, we recommend you check out our free course on open source: ibm.biz/opensourcecourse

**Comment by dmtrek14** [comment]
@demilolu Created. I can't assign it to myself or add labels, so if you could handle that part, I'd appreciate it. It's #117
