### ISSUE TITLE
Do you have a  UI Feature Update? | Start Here

### ISSUE THREAD

**Issue by demilolu** [Call-for-Code-for-Racial-Justice/Legit-Info#101]
## Background

This issue provides directions on how you can contribute to Legit-Info by suggesting feature updates. Please keep this issue open.

## Tasks

- [ ] Check out the open issues, ensure you're not replicating existing issues
- [ ] Read & follow the instructions in the [Getting Started section ](https://github.com/Call-for-Code-for-Racial-Justice/Legit-Info#getting-started)of the readme.md to set the solution up  

As you run the solution, note any updates to current UI features that would improve the user experience with this solution
- [ ] create a new issue using the feature updatetemplate
- [ ] label it 'hacktoberfest', ''front end'
- [ ] Discuss your suggested feature  the issue with @upkarlidder @tonypearson @demilolu 

If you are able to implement the solution
- [ ] assign yourself to the issue
- [ ] add details on your proposed fix to the issue
- [ ] Discuss the issue  with @upkarlidder @tonypearson @demilolu 
- [ ] submit a pull request to main branch
- [ ] PR merged by Legit-Info team
- [ ] Congratulations! 

If you are unfamilar with pull requests, committing code on Github, we recommend you check out our free course on open source: ibm.biz/opensourcecourse
