### ISSUE TITLE
Create GitHub actions to test new code before merging

### ISSUE THREAD

**Issue by demilolu** [Call-for-Code-for-Racial-Justice/Legit-Info#102]
### Background on the problem the feature will solve/improved user experience
Add GitHub Actions to test and build new code pushed to a branch or committed to a pull request. Code that passes all the steps in the GitHub action can be merged in the repository.

### Describe the solution you'd like
A GitHub action runs whenever code is committed to any branch or PR is made to the main branch. We need actions for
- [ ] **services**
- [ ] UI

Each action will 
- [ ] install dependencies 
- [ ] build for production 
- [ ] run all tests 
- [ ] linting, we haven't chosen a linter so let's discuss options in the comments

### Tasks
- [ ] Ensure install, build and lint steps run locally on your system
- [ ] Read more about [GitHub actions](https://docs.github.com/en/actions/learn-github-actions), in the Build and Test section
- [ ] Create GitHub actions for each folder described above. You can read more [JavaScript build actions here](https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs-or-python).
- [ ] Commit and push your GitHub action code.
- [ ] Go to the [Actions tab](https://github.com/Call-for-Code-for-Racial-Justice/Legit-Info/actions) to see if it worked.

### Acceptance Criteria 
GitHub action runs for every new code commit and PR.

@upkarlidder

**Comment by demilolu** [comment]
this has been done in another PR
