### ISSUE TITLE
Legit-Info Documentation Updates

### ISSUE THREAD

**Issue by demilolu** [Call-for-Code-for-Racial-Justice/Legit-Info#138]
## Background

Legit-Info has extensive documentation on frontend application and backend services. We would like you try out the application and suggested improvements to the documentation. 

During this cohort your team members will also be making updates to the Legit-Info application. We would like to document these new changes in our documentation as well. 

## Tasks
Adding new documentation
- [ ] Discuss with Legit-Info cohort members to understand changes to Legit-Info application
- [ ] Create a new issue using the documentation templates
 - [ ] label it  'documentation' 'ms-cohort-claimed' and assign the issue to yourself,
- [ ] Discuss your changes in the issue 

Fixing existing Documentation
- [ ] Check out the open documentation issues
- [ ] Read & follow the instructions in the Getting Started section of the readme.md to set the solution up 
If any directions are unclear, outdated:
- [ ] create a new issue using the documentation template
- [ ] label it  'documentation' 'ms-cohort-claimed' and assign the issue to yourself,
- [ ] Discuss your changes in the issue
